#!/bin/bash

SCRIPTS=$(curl https://raw.githubusercontent.com/rscotton/laboratory/master/scripts/scriptlist.txt)

mkdir -p ~/bin
cd ~/bin

echo '#######################################'
echo '         getting scripts...'
echo '#######################################'
echo
for script in $SCRIPTS;
do
    echo "Downloading $script to $HOME/bin/$script ..."
    curl https://raw.githubusercontent.com/rscotton/laboratory/master/scripts/$script > $script
    chmod 755 $script
done

echo
echo '#######################################'
echo '               DONE!!!'
echo '#######################################'
echo

cd -;