#!/bin/bash

SCRIPTS="mysqli
build-local-config
plogin
pclone
pdb
pfiles
pgetsite
rewritebase.py
remove-short-tags.pl
getscripts"

mkdir -p ~/bin
cd ~/bin

echo '#######################################'
echo '         getting scripts...'
echo '#######################################'
echo
for script in $SCRIPTS;
do
    echo "Downloading $script to $HOME/bin/$script ..."
    curl https://raw.githubusercontent.com/rscotton/laboratory/master/scripts/$script > $script
    chmod 777 $script
done

echo
echo '#######################################'
echo '               DONE!!!'
echo '#######################################'
echo

cd -;