#!/bin/bash

# Note: $LOCAL_DEV_DIR must be set in .bash_profile for this to work properly

set -e # exit immediately if command exits with a non-zero status

# Save current directory to return to at end of script
START_DIR="$PWD"

# Change into site root if provided
if [ -z "$1" ]
then
	echo "No site directory name provided, using current directory..."
else
	cd $LOCAL_DEV_DIR/$1
fi;

# Gather site root, site name, CMS type
ROOT=$(drush ev "print DRUPAL_ROOT")
if [ "$ROOT" = "DRUPAL_ROOT" ] # meaning it's not defined in the context of where this script ran
then
	echo "Not a Drupal build, attempting to grab Wordpress root..."
	ROOT=$(wp eval "print get_home_path();") # grab code root
	CMS="Wordpress"
	CMS_VERSION=$(wp core version)
else
	CMS="Drupal"
	CMS_VERSION=$(drush status drupal-version --format=list)
fi;
echo "Confirmed CMS: $CMS $CMS_VERSION"
ROOT=${ROOT%/} #strip trailing slash
echo "Root: $ROOT"
SITE=${ROOT##*/} #grab trailing directory name
echo "Site: $SITE"

# Use terminus to get the Pantheon Site ID
SITE_PID=$(terminus site:info --field="id" $SITE)
echo "Pantheon Site Id: $SITE_PID"

# Determine Site environment
if [ -z "$2" ]
then
    ENV="dev"
else
    ENV=$2
fi;
echo "Pantheon Environment: $ENV"

# Determine the local database name
cd $LOCAL_DEV_DIR/$SITE
if [ "$CMS" = "Drupal" ]
then
	DB_NAME=$(drush status db-name --format=list)
else # Wordpress
	DB_NAME=$(wp eval 'echo DB_NAME;')
fi;
echo "Local Database: $DB_NAME"

# Ensure sqltemp directory exists, remove any previous database files that might be lingering
mkdir -p $HOME/sqltemp
rm -f $HOME/sqltemp/${SITE}*.sql.gz

# Create a new database backup and download it to sqltemp
terminus backup:create --element=database $SITE.$ENV
terminus backup:get --element=database --to=${HOME}/sqltemp/${SITE}.sql.gz $SITE.$ENV

# Import database, remove backup file
mysqli $DB_NAME $HOME/sqltemp/${SITE}.sql.gz
rm -f $HOME/sqltemp/${SITE}*.sql.gz

# Change back to original directory
cd $START_DIR;

# Celebrate!
osascript -e "display notification \"SQL synced for $SITE\" with title \"SQL synced!\"";
#say "sequel synced";