#!/bin/bash

#Note that $LOCAL_DEV_DIR must be set in .bash_profile for this to work

#TODO: Rewrite to accommodate Wordpress AND Drupal!

set -e # exit immediately if command exits with a non-zero status

if [ -z "$1" ]
then
    ROOT=$(wp eval "print get_home_path();") #grab code root
    ROOT=${ROOT%/} #strip trailing slash
    echo "Root: $ROOT"
    SITE=${ROOT##*/} #grab trailing directory name
else
    SITE=$1
fi;
echo "Site: $SITE"

SITE_PID=$(terminus site info --site="$SITE" --field="id")
echo "Pantheon Site Id: $SITE_PID"

if [ -z "$2" ]
then
    ENV="dev"
else
    ENV=$2
fi;
echo "Pantheon Environment: $ENV"

cd $LOCAL_DEV_DIR/$SITE
DB_NAME=$(wp eval 'echo DB_NAME;')

mkdir -p $HOME/sqltemp
rm ~/sqltemp/$SITE*.sql.gz > /dev/null 2>&1 ||

terminus site backups create --element=database --site=$SITE --env=$ENV &&
terminus site backups get --element=database --site=$SITE --env=$ENV --to=$HOME/sqltemp --latest &&

mysqli $DB_NAME ~/sqltemp/$SITE*.sql.gz
rm ~/sqltemp/$SITE*.sql.gz

cd -;
osascript -e "display notification \"SQL synced for $SITE\" with title \"SQL synced!\"";
#say "sequel synced";